### ISSUE TITLE
Extension Addon (Blender 4.2) Preferences show "Warning /\ Policy violation with top level module: <addon_id>

### ISSUE THREAD

**Issue by TomErnst** [JacquesLucke/blender_vscode#181]
After many good experiences with making addons I am creating my first "extension" right now, via the VSCode-addon, using an adapted version of the VSCode-addon generated "blender_manifest.toml".
Since somewhere during my development process (can't find out, when exactly) the extension shows a warning text in the preference editor.
I have checked the "blender_manifest.toml" thoroughly, but can't find out the reason, blender documentation was no help in this case.
Also the terminal output gives no hints.
What may I have done wrong, resp. what can I do to find the fault?

**Comment by Mateusz-Grzelinski** [comment]
Hello again.
Is it the full error?
No output in logs is rare situation. So I will need you to isolate the issue a bit by using some env vars:
```
    "blender.environmentVariables": {
        "BLENDER_USER_CONFIG": "./blender_isolation",
        "BLENDER_USER_SCRIPTS": "./blender_isolation",
        "BLENDER_USER_EXTENSIONS": "./blender_isolation"
    },
```
In source code of blender I found the test: https://projects.blender.org/blender/blender/src/branch/main/scripts/addons_core/bl_pkg/tests/test_cli_blender.py#L778
```
        Warn when:
        - extensions add themselves to the ``sys.path``.
        - extensions add top-level modules into ``sys.modules``.
```

**Comment by TomErnst** [comment]
Many many thanks, I had added the module to sys.modules (to not having to "import bl_ext.user_default.<id>" as <id>" each time after Blender start).  I removed it … that was it.
If you have an idea how to solve the problem above, please tell me.
Thanks again, the issue can be closed :)

**Comment by TomErnst** [comment]
btw, beside your other detailed answers in the other issue thread before also your last comment was brilliant and led me onto new trails (this one here one of them \**grins\**), especially concerning generic matters. Thanks again for dealing your knowledge so detailed.

**Comment by Mateusz-Grzelinski** [comment]
> that also bpy.props.* have to be defined as annotations

yup. That was a change that was made a long time ago. Used to be normal class variable. I really dont know why they would use annotations for this...

Remember that many blender python typing corner cases were already worked on/solved by https://github.com/nutti/fake-bpy-module.

>  If you have an idea how to solve the problem above (i.e. how to get the main <id> being automatically imported for the debug window, best also after each update), please tell me.

I do not understand. What do you mean  `for the debug window`? There is a python trick for TYPE_CHECKING https://github.com/JacquesLucke/blender_vscode/blob/master/pythonFiles/launch.py#L12 but not sure where you are going with this. 

> I even found a method to avoid the "register" mess 

Yup, sounds familiar. Usually registering is some combination of 
1. Gather your classes in one place (usually a tuple of classes to register)
2a. register (and do not mess up the order)
2b. Make your registering super exotic and unique. Be Proud of your achievement. Fix it because you found a corner cases (like #118). Be proud again.

Be amazed by this exitic piece of code:
```
# scripts/addons_core/rigify/operators/__init__.py
def register():
    # Lazily load modules to make reloading easier. Loading this way
    # hides the submodules and their dependencies from initial_load_order.
    loaded_submodules[:] = [
        importlib.import_module(__name__ + '.' + name) for name in submodules
    ]

    for mod in loaded_submodules:
        mod.register()
```

You are lucky because I just was looking for distraction from my usuall DevOps-y work and I for a long time wanted to change some things in this repo. I just finished my (yet another) studies and got some time to look at random issues.
