### ISSUE TITLE
ModuleNotFoundError 

### ISSUE THREAD

**Issue by Radivarig** [JacquesLucke/blender_vscode#23]
I'm running blender 2.80 from docker like this:
```sh
#!/bin/sh
exec \
  docker run -t \
  -e ADDON_DIRECTORIES_TO_LOAD \
  -e EDITOR_PORT \
  -e ALLOW_MODIFY_EXTERNAL_PYTHON \
  -e DISPLAY \
  -v /tmp/.X11-unix:/tmp/.X11-unix \
  -v /home/radivarig/:/home/radivarig \
  --network="host" \
  --device /dev/snd \
  ubuntu/blender:version3 \
  ./home/radivarig/projects/blender-env/blender-2.80-4dd0a90f4213-linux-glibc224-x86_64/blender "$@" \
```
I select it as blender executable after running `Blender: Start`, blender does opens but throws:
```
File "/home/radivarig/projects/blender-env/blender-2.80-4dd0a90f4213-linux-glibc224-x86_64/2.80/scripts/modules/addon_utils.py", line 351, in enable
    mod = __import__(module_name)
ModuleNotFoundError: No module named 'TestAddon'
```
The addon symlink is created under `'/root/.config/blender/2.80/scripts/addons'` inside the docker container and when I reset to factory settings or open blender by hand enabling the addon does work.

Any ideas?

**Comment by JacquesLucke** [comment]
Unfortunately I have no experience with Docker, so I don't know how it might impact the extension.

How is your addon structured?

When you start Blender the normal manually, can the addon load when it is symlinked into the addon directory?

Is it possible that docker somehow redirects the symlink, so that Blender can't find your source code files?

**Comment by JacquesLucke** [comment]
hmm ok, I'm confused.
I don't really have any idea why this is happening right now, sry..

**Comment by jessey-git** [comment]
It's probably not related to docker.  I've seen this happen as well on raw win10.  For me it happened because I started with a completely blank Blender config directory and attempted to launch blender with my addon right away from vscode.  To fix this I had to launch blender by itself first, and then enable my addon manually.

After that I was able to use the vscode extension normally.  It seems that the extension has trouble if the addon doesn't exist yet?

**Comment by JacquesLucke** [comment]
Maybe, have to check that. You mean that the "addons" directory does not exist yet?

**Comment by jessey-git** [comment]
I mean the entire C:\Users\_username_\AppData\Roaming\Blender Foundation\Blender\2.80 hierarchy doesn't exist -- this includes the top-level "config" and "scripts" directories which would also include addons.

I do this every ~2 weeks to ensure I'm loading true beta defaults everywhere etc.

**Comment by Radivarig** [comment]
@jessey-git that was it! I've started it once, did docker commit and the extension works. Thanks!

**Comment by jessey-git** [comment]
I'd actually vote to keep the issue open as it's a bug in the extension that could be fixed I think

**Comment by schlegel11** [comment]
Hi,
I found this great visual studio plugin the last days :smiley: 
Unfortunately I got the here described ModuleNotFoundError exception under the same circumstances @jessey-git describes here https://github.com/JacquesLucke/blender_vscode/issues/23#issuecomment-452077770.
I think I fixed the issue and added a pull request #42. 
(Which is already merged ... holy cow that was fast :smile: )

Greetings

**Comment by Radivarig** [comment]
@schlegel11 thanks!

**Comment by Radivarig** [comment]
@jessey-git could you publish an update to the vscode market?

**Comment by gmagno** [comment]
Just in case it helps someone, a `ModuleNotFoundError` will be thrown if the blender version is not correctly specified inside the addon's `__init__.py.bl_info`, so it is worth double checking that:
```
bl_info = {
    # ...
    "blender" : (2, 80, 0),  # <-- as opposed to (common mistake): (2, 8, 0)
    # ...
}
```

**Comment by Mrinny5** [comment]
Same issue.
![blender error](https://user-images.githubusercontent.com/40122791/96027932-4581db00-0e76-11eb-8706-7cf53659b626.png)
