### ISSUE TITLE
Add-on inside Blender not showing (features like "New Panel" )

### ISSUE THREAD

**Issue by Hanjocl** [JacquesLucke/blender_vscode#30]
Hi, I'm really new to writing addons for Blender and found this amazing addon for VS code. I had some trouble with getting blender to start up and it turned out that VS code didn't have acces to the "program" folder so I cpoied Blender to a folder inside "documents" and it worked!!

Yesterday I watched the video ([this one](https://www.youtube.com/watch?v=WbHN8w7GbJ0)) you(Jacques Luke) did on the addon. it shows inside blender a addon that writes panels to VS code. I was immediate excited to use this feature but when I started blender it didn't show up.

So maybe someone knows why the addon inside blender isn't showing up? and how I can solve it so I can use this great addon for coding?(I hope I'm asking the right questions)

**Comment by JacquesLucke** [comment]
Unfortunately, this feature turned out to be less useful in practice than I thought at first. Also it was not polished enough to release it. So I decided to remove it.
I prefer the way operators are created more now. This is not implemented for panels yet. Should not be very hard, there are just quite a few more cases to consider than with operators.
