### ISSUE TITLE
command 'blender.start' not found

### ISSUE THREAD

**Issue by joshuaKnauber** [JacquesLucke/blender_vscode#34]
Everything was working fine until I opened a different addon folder and then switched back to my original addon folder.
Now this message (command 'whatever_the_command_is' not found) appears for every command that this extension has.
I tried reinstalling the extension and restarting vs code and my computer but that didn't help.

**Comment by FrankEscobar** [comment]
Same problem here I think that it has something to do with a VS Code update.

**Comment by joshuaKnauber** [comment]
I tried downgrading vs code to 1.32 and 1.31 but that didn't change anything.

**Comment by joshuaKnauber** [comment]
Ok, so for some reason it's working again. These are the things I did:
- Install a previous version of VS code
- Go to the settings.json file and clear the list of blender executables
- Reinstall the extension
-Update VS code

I have no idea which of those things made it work again..

**Comment by JacquesLucke** [comment]
Thanks for the update. Not sure if there is anything I can do about it. Closing for now.

**Comment by needabetterusername** [comment]
Just FYI if anyone finds this.

I recently had this problem when returning to development after some time. I am using mac.

This solution worked for me:
1) Run vscode under sudo, because I encountered some strange permissions errors during my attempt.
2) Replace all versions of Blender executables in user's settings.json because I had since deleted those (old versions)
3) Add python executable path for target Blender version
4) Deleted unnecessary workspace settings.json file. Somehow it was created (probably my fault) with an empty list of executables, this caused an additional vscode error (something "error reading from undefined"). 
5) Restart vs code

Also there was a vscode update in the meantime which might have complicated things.
