### ISSUE TITLE
back_to_previous() crashes blender

### ISSUE THREAD

**Issue by kromar** [JacquesLucke/blender_vscode#81]
System Information
Operating system: Windows-10-10.0.19041-SP0 64 Bits
Graphics card: Radeon (TM) RX 480 Graphics ATI Technologies Inc. 4.5.14736 Core Profile Context 20.10.1 27.20.12033.1007

Blender Version
Broken: version: 2.90.1, branch: master, commit date: 2020-09-23 06:43, hash: rB3e85bb34d0d7
Worked: --

Short description of error
when i use bpy.ops.screen.back_to_previous() in a addon blender crashes about every 5th time.

Exact steps for others to reproduce the error
1. start visual studio code
2. run blender from visual studio and run the script from the text editor, that should trigger the crash.
```
import bpy

i=0
while i < 1000: 
    for window in bpy.context.window_manager.windows:
        screen = window.screen
        for area in screen.areas:
            if area.type == 'VIEW_3D':             
                view_3d = area.spaces.active.region_3d
                override = {'window': window, 'screen': screen, 'area': area}                    
                bpy.ops.screen.screen_full_area(override)   

    bpy.ops.screen.back_to_previous()  
    print("loop:", i)
    i+=1
```

**Comment by Mateusz-Grzelinski** [comment]
I am not surprised that blender dies after performing 1000 times operation with `bpy.ops` which should not be used in scripts anyway. 
Communication with VS code is done by blender timers api which can not execute because you are giving them a lot of work to do and windows console is slow at printing anyways.
It crashes blender regardless if blender is started from VS code. 
Closing as invalid.
